<?php
$z[0]=Array("arcurl","",48,63);
$z[1]=Array("title","",72,86);
$z[2]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",88,242);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",333,348);
$z[4]=Array("title","",357,371);
$z[5]=Array("title","",373,387);
$z[6]=Array("pubdate","",398,445);
$z[6][4]['function']="MyDate('y.m.d',@me)";
$z[7]=Array("description","",494,514);
$z[8]=Array("arcurl","",526,541);
$z[9]=Array("click","",636,650);

?>