
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:telphone itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:telphone>

<field:demand itemname="需求信息" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:demand>

<field:companyname itemname="公司地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:companyname>

<field:sex itemname="性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>
