<li>
              <div class="newtp"><a href="[field:arcurl/]" title="[field:title/]">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]</a></div>
              <div class="newwz">
                <div class="nztit"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a><span>/[field:pubdate function="MyDate('y.m.d',@me)"/]</span></div>
                <div class="nzms">[field:description/]...<a href="[field:arcurl/]">详细</a></div>
                <div class="nwwz_bot">
                  <div class="nw1">查看次数：[field:click/]</div>
                </div>
              </div>
            </li>