<?php
$z[0]=Array("item","",4,94);
$z[0][4]['name']="默认模板管理";
$z[0][4]['link']="templets_main.php";
$z[0][4]['rank']="temp_All";
$z[0][4]['target']="main";
$z[1]=Array("item","",98,193);
$z[1][4]['name']="标签源码管理";
$z[1][4]['link']="templets_tagsource.php";
$z[1][4]['rank']="temp_All";
$z[1][4]['target']="main";
$z[2]=Array("item","",197,286);
$z[2][4]['name']="自定义宏标记";
$z[2][4]['link']="mytag_main.php";
$z[2][4]['rank']="temp_MyTag";
$z[2][4]['target']="main";

?>