<?php
$z[0]=Array("global","",102,134);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("flink","  [field:link /]|  ",396,475);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",570,596);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",662,683);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("global","",742,774);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",882,914);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1019,1043);
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",1067,1092);
$z[7][4]['name']="cfg_tongji";
$z[8]=Array("global","",1546,1572);
$z[8][4]['name']="cfg_kefutel";
$z[9]=Array("global","",1656,1677);
$z[9][4]['name']="cfg_qq";
$z[10]=Array("global","",2365,2397);
$z[10][4]['name']="cfg_templets_skin";

?>