<?php
$z[0]=Array("flink","  [field:link /]|  ",219,298);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",395,421);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",487,508);
$z[2][4]['name']="cfg_qq";
$z[3]=Array("global","",567,599);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",707,739);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",899,923);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",951,976);
$z[6][4]['name']="cfg_tongji";
$z[7]=Array("global","",1420,1446);
$z[7][4]['name']="cfg_kefutel";
$z[8]=Array("global","",1663,1684);
$z[8][4]['name']="cfg_qq";

?>