<?php
$z[0]=Array("flink","  [field:link /]|  ",214,293);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",386,412);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",478,499);
$z[2][4]['name']="cfg_qq";
$z[3]=Array("global","",558,590);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",698,730);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",835,859);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",883,908);
$z[6][4]['name']="cfg_tongji";
$z[7]=Array("global","",1352,1378);
$z[7][4]['name']="cfg_kefutel";
$z[8]=Array("global","",1595,1616);
$z[8][4]['name']="cfg_qq";

?>