<?php
$z[0]=Array("global","",102,134);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("flink","  [field:link /]|  ",401,480);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",579,605);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",671,692);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("global","",751,783);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",891,923);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1083,1107);
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",1135,1160);
$z[7][4]['name']="cfg_tongji";
$z[8]=Array("global","",1614,1640);
$z[8][4]['name']="cfg_kefutel";
$z[9]=Array("global","",1724,1745);
$z[9][4]['name']="cfg_qq";
$z[10]=Array("global","",2433,2465);
$z[10][4]['name']="cfg_templets_skin";

?>