<?php
$z[0]=Array("arclist"," <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a> \r\n               ",341,486);
$z[0][4]['row']="3";
$z[0][4]['titlelen']="32";
$z[0][4]['typeid']="11";
$z[1]=Array("channelartlist","\r\n        \r\n        <li class=\"\"><a href=\"{dede:field name='typeurl'/}\" class=\"\">{dede:field name='typename'/}</a>\r\n          <ul id=\"nav1\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li> <a href=\"[field:typelink/]\">[field:typename/]</a> </li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>\r\n        ",572,965);
$z[1][4]['typeid']="top";

?>