<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><!-- //底部模板 -->
<div class="footer w960 center mt1 clear">
	<!-- 
		为了支持织梦团队的发展,请您保留织梦内容管理系统的链接信息.
		我们对支持织梦团队发展的朋友表示真心的感谢!织梦因您更精彩!
	-->
    <div class="footer_left"></div>
    <div class="footer_body">
	<p class="powered">    
		Powered by <a href="http://www.dedecms.com" title="织梦内容管理系统(DedeCms)--国内最专业的PHP网站管理系统，轻松建站的首选利器。" target="_blank"><strong>DedeCMS<?php echo $GLOBALS['cfg_version']; ?></strong></a> &copy; 2004-2011 <a href="http://www.desdev.cn/" target="_blank">DesDev</a> Inc.<br /><div class="copyright"><?php echo $GLOBALS['cfg_powerby']; ?>&nbsp;&nbsp;<?php echo $GLOBALS['cfg_beian']; ?><script language="javascript">document.write(unescape('%3Cscript%20language%3D%22javascript%22%3Evar%20www_helpor_net%3D%22%25u6280%25u672F%25u652F%25u6301%25uFF1A%253Ca%2520href%253D%2522http%253A//%252577%252577%252577%25252E%252577%252561%25256C%252573%252565%25256F%25252E%252563%25256F%25256D/%2522%2520target%253D%2522_blank%2522%2520title%253D%2522%25u7F51%25u5320%25u7F51%25u7EDC%25u8425%25u9500%2522%253E%25u7F51%25u5320%25u7F51%25u7EDC%25u8425%25u9500%253C/a%253E%22%3Bwww_Helpor_net%3Dunescape%28www_helpor_net%29%3Bdocument.write%28www_Helpor_net%29%3B%3C/SCRIPT%3E'));</SCRIPT></div></p>        
<!-- /powered -->
   </div>
   <div class="footer_right"></div>
</div>